### PR TITLE
error json + reports stats on number of files processed

### LINKED ISSUE #293: report number of files parsed or ignored
When we invoke sgrep with --json, it would be great to have a statistics section that gives us a sense of the number of files that were parsed, failed to parse, or were ignored.

### PR DESCRIPTION
**Pull request by ievans**
There were some bugs where errors weren't coming through in the json output. Now they do! Useful for sgrep.live, cc @DrewDennison `--json` will now put output into an `errors` key that we can actually use to highlight ranges in the intput source code

I removed error filtering in sgrep-core so that it can happen in sgrep.py later.

closes #293

### CODE REVIEW

File: sgrep/bin/main_sgrep.ml [hunk 1]
```diff
@@ -423,6 +427,7 @@ let options () =
     "-rules_file", Arg.Set_string rules_file,
     " <file> obtain list of patterns from YAML file";
 
+    "-json", Arg.Set output_format_json, "output to JSON";
```
Comment (ievans) [inline sgrep/bin/main_sgrep.ml]: @aryx I couldn't find an easy way to make the one_pattern also output json. Seems some refactoring of the output logic would be useful to make this work. Difficult because of the stream vs collecting output model between the lint vs not lint approach right now.
